HEADER:
  label: "Portfolio"

PROJECTS:
  - title: "STING: Segmenting Transcriptomics in Neighborhoods of Genes"
    category: ["Bioinformatics", "R", "Package"]
    image: "https://i.imgur.com/lAmQAAM.jpeg"
    url: "https://github.com/nishcomp/STING"