HEADER:
  label: "CV"

PDF_CV:
  enabled: true
  title: "My CV"
  description: "View my complete CV below. You can also download it for offline viewing."
  button_text: "Download CV (PDF)"
  pdf_url: "config/assets/Nischal_Bhandari_CV.pdf"
  icon: "download-outline"
  show_preview: true
  preview_height: "800px"

# Legacy sections - disabled by default
EDUCATION:
  enabled: false
  label: "Education"
  items: []

EXPERIENCE:
  enabled: false
  label: "Experience"
  items: []

LANGUAGES:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items: []

SKILLS:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items: []
