HEADER:
  label: "CV"

# Legacy sections - enabled by default
EDUCATION:
  enabled: true
  label: "Education"
  items: []

EXPERIENCE:
  enabled: true
  label: "Research Experience"
  items: []

LANGUAGES:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items: []

SKILLS:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items: []

PDF_CV:
  enabled: true
  title: ""
  description: ""
  button_text: "Download CV (PDF)"
  pdf_url: "config/assets/Nischal_Bhandari_CV.pdf"
  icon: "download-outline"
  show_preview: true
  preview_height: "800px"